version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - PREFIX=api
  dongstage:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: dongstage
    ports:
      - 3000:80
    environment:
      - VITE_APP_PORT=3000
      - VITE_SERVER_URL=http://server:8080
